#!/bin/bash

SORT_COLUMN=1
[[ "$1" == "by-name" ]] && SORT_COLUMN=2

samba-tool gpo listall -H /var/lib/samba/private/sam.ldb | \
    awk 'BEGIN{RS="\n\n";FS="\n"} {print $1 " : " $2}' | \
    awk -F ' : ' '{print $2 " " $4}' | \
    sort -k ${SORT_COLUMN}
