#!/bin/bash

[[ $# -ne 1 ]] && echo "Usage: $0 <uuid>" && exit 1
UUID="$1"
DOMAIN="$(dnsdomainname)"
BASE_DN="DC=$(echo $DOMAIN | sed 's/\./,DC=/g')"

echo "Removing LDAP objects at: ${BASE_DN}"
ldbdel -H /var/lib/samba/private/sam.ldb "CN=Machine,CN={${UUID}},CN=Policies,CN=System,${BASE_DN}"
ldbdel -H /var/lib/samba/private/sam.ldb "CN=User,CN={${UUID}},CN=Policies,CN=System,${BASE_DN}"
ldbdel -H /var/lib/samba/private/sam.ldb "CN={${UUID}},CN=Policies,CN=System,${BASE_DN}"
