#!/bin/bash
# When running from cron PATH is not set
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#
#  Download scripts: chgkrbtgtpass chgtdcpass 
#  from: https://gitlab.com/samba-team/samba/-/raw/master/source4/scripting/devel/<script>
#
# Schedule this in cron-monthly

if samba-tool drs showrepl | grep 'Last attempt' | grep -q 'failed'; then
    echo "DRS Replication is failing, dc and krbtgt passwords not changed!"
    exit 1
fi

if has_fsmo_roles; then
    # change krbtgt account password
    chgkrbtgtpass
    # change machine account password
    chgtdcpass
    # restart to DC after password change to prevent NT_STATUS_WRONG_PASSWORD
    systemctl restart samba-ad-dc
    exit 0
fi

# Wait until the DC with FSMO-roles has replicated 
sleep 15m

if samba-tool drs showrepl | grep 'Last attempt' | grep -q 'failed'; then
    echo "DRS Replication is failing, dc-machine-account passwords not changed!"
    exit 1
fi
# change machine account password
chgtdcpass
# restart to DC after password change to prevent NT_STATUS_WRONG_PASSWORD
systemctl restart samba-ad-dc
