#!/bin/bash

DNS_DOMAIN="$(dnsdomainname)"
SYSVOL_PATH="/var/lib/samba/sysvol/${DNS_DOMAIN}"

function cleanup() {
    rm "${ACL_DIRS_FILE}" 2> /dev/null
    rm "${ACL_FILES_FILE}" 2> /dev/null
}

function flags_to_mode() {
    if grep -q '^# flags:' "${ACL_DIRS_FILE}"; then
        awk 'BEGIN{ORS=","} /# flags: .s./{print "g+s"}/# flags: .-./{print "g-s"} /# flags: ..t/{print "o+t"}/# flags: ..-/{print "o-t"}' "${ACL_DIRS_FILE}" | sed -e 's/,$//'
    else
        echo "g-s,o-t"
    fi
}    

function set_sysvol_subtree_permissions() {
    local DIR=$1
    
    getfacl "${DIR}" > "${ACL_DIRS_FILE}"
    grep '^default' "${ACL_DIRS_FILE}" | cut -d : -f 2- > "${ACL_FILES_FILE}"
    MODE_FLAGS="$(flags_to_mode)"
    SHARE_GROUP="$(stat -c '%G' "${DIR}")"

    find "${DIR}/" \
        -mindepth 1 \
        -type d \
        -print \
        -exec chmod "${MODE_FLAGS}" "{}" \; \
        -exec chgrp "${SHARE_GROUP}" "{}" \; \
        -exec setfacl -b "{}" \; \
        -exec setfacl --set-file="${ACL_DIRS_FILE}" "{}" \; -print

    find "${DIR}/" \
        -mindepth 1 \
        -type f \
        -print \
        -exec chgrp "${SHARE_GROUP}" "{}" \; \
        -exec setfacl -b "{}" \; \
        -exec setfacl --set-file="${ACL_FILES_FILE}" "{}" \;   
}

function propagate_sysvol_gpo_permissions {
    local DIR=$1
    GPO_PATHS="$(find "${DIR}/" -mindepth 1 -maxdepth 1 -name '{*}')"
    for GPO_PATH in ${GPO_PATHS}; do
        GPO_NAME="$(basename "${GPO_PATH}" | awk -F . '{print $1}')"
        echo "================="
        echo "GPO: ${GPO_NAME}"

        getfacl "${GPO_PATH}" 2>/dev/null > "${ACL_DIRS_FILE}"
        grep '^default' "${ACL_DIRS_FILE}" | cut -d : -f 2- > "${ACL_FILES_FILE}"
        OWNER_NAME="$(awk '/# owner:/{sub(/\\040/," ",$3); sub(/\\\\/,"\\", $3); print $3}' "${ACL_DIRS_FILE}")"
        GROUP_NAME="$(awk '/# group:/{sub(/\\040/," ",$3); sub(/\\\\/,"\\", $3); print $3}' "${ACL_DIRS_FILE}")"
        MODE_FLAGS="$(flags_to_mode)"

        echo "Set directory permissions"
        find "${GPO_PATH}/" \
            -mindepth 1 \
            -type d \
            -print \
            -exec chmod "${MODE_FLAGS}" "{}" \; \
            -exec chown "${OWNER_NAME}":"${GROUP_NAME}" "{}" \; \
            -exec setfacl -b "{}" \; \
            -exec setfacl --set-file="${ACL_DIRS_FILE}" "{}" \;

        echo
        echo "Set file permissions"
        find "${GPO_PATH}/" \
            -mindepth 1 \
            -type f \
            -print \
            -exec chown "${OWNER_NAME}":"${GROUP_NAME}" "{}" \; \
            -exec setfacl -b "{}" \; \
            -exec setfacl --set-file="${ACL_FILES_FILE}" "{}" \;   
    done 
}

function main() {
    ACL_DIRS_FILE="$(mktemp)"
    ACL_FILES_FILE="$(mktemp)"
    trap cleanup EXIT SIGTERM SIGINT

    set_sysvol_subtree_permissions "${SYSVOL_PATH}/scripts"
    set_sysvol_subtree_permissions "${SYSVOL_PATH}/Policies/PolicyDefinitions"
    propagate_sysvol_gpo_permissions "${SYSVOL_PATH}/Policies"
}

# shellcheck disable=SC2068
main $@
